const mongoose = require('mongoose');

const incidentSchema = new mongoose.Schema({
    reporterId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    reportedId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    matchId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Match',
    },
    threatLevel: {
        type: Number,
        enum: [0, 1, 2, 3], // 0 = Clean, 1 = Mild (Warning), 2 = Moderate (Temp Ban), 3 = Severe (Perma Ban)
        required: true
    },
    description: {
        type: String, // Context generated by GuardianShield or manual report
    },
    status: {
        type: String,
        enum: ['open', 'resolved'],
        default: 'open'
    }
}, { timestamps: true });

const Incident = mongoose.model('Incident', incidentSchema);
module.exports = Incident;
